//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace BLL.DTOQuery
{
    public partial class CidadeDTOQuery
    {
        #region Navigation Properties
    
        public EstadoDTOQuery Estado()
        {
            if (_estado == null)
            {
                _estado = new EstadoDTOQuery();
            }
            return _estado;
        }
        public EstadoDTOQuery _estado;

        #endregion
    }
}
