//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace BLL.DTOQuery
{
    public partial class PerfilDTOQuery
    {
        #region Navigation Properties
    
        public LoginDTOQuery Login()
        {
            if (_login == null)
            {
                _login = new LoginDTOQuery();
            }
            return _login;
        }
        public LoginDTOQuery _login;
    
        public SubMenuDTOQuery SubMenu()
        {
            if (_subMenu == null)
            {
                _subMenu = new SubMenuDTOQuery();
            }
            return _subMenu;
        }
        public SubMenuDTOQuery _subMenu;

        #endregion
    }
}
