//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

using DAL;
using Model;
using BLL.DTOAssembler;
using BLL.DTOQuery;

namespace BLL
{
    public partial class CidadeBLL : BaseBLL
    {
    	DAL.Cidade m_Data;
    
    	public CidadeBLL(DAL.Cidade p_Data)
    	{
    		this.m_Data = p_Data;
    	}
    
    	public override Model.BaseModel getModel()
    	{
    		if(this.m_Data == null)
    			return null;
    
    		Model.CidadeModel v_Return = new Model.CidadeModel();
    				v_Return.Id = this.m_Data.Id;
    		v_Return.Nome = this.m_Data.Nome;
    		v_Return.ComboboxText = this.m_Data.ComboboxText;
    		return v_Return;
    	}
    
    	public Model.CidadeModel getModelComplete()
    	{
    		Model.CidadeModel v_Return = (Model.CidadeModel) getModel();
    		if(v_Return == null)
    			return null;
    
    		v_Return.Estado = getEstado();
    		return v_Return;
    	}
    
    	internal EstadoModel getEstado()
    	{
    		EstadoModel v_Model = new EstadoModel();
    		if (v_Model != null && m_Data != null && m_Data.Estado!= null)
    		{
    			v_Model = (EstadoModel)(new BLL.EstadoBLL(m_Data.Estado).getModel());
    		}
    		return v_Model;
    	}
    	public static CidadeModel GetCidade(int p_Identifier)
    	{
    		Cidade v_Data = Cidade.GetCidade(p_Identifier);
            return  ( CidadeModel)(new BLL.CidadeBLL(v_Data).getModelComplete());
    	}
    
    	public static CidadeModel GetCidade(int p_Identifier, CidadeDTOQuery p_Query)
    	{
    		Cidade v_Data = Cidade.GetCidade(p_Identifier);
    		return (new CidadeDTOAssembler()).Create(v_Data, null, p_Query);
    	}
    
    	public static ICollection<CidadeModel> ListCidade()
    	{
    		ICollection<CidadeModel> v_ReturnList = new Collection<CidadeModel>();
    		ICollection<Cidade> v_Data = Cidade.ListCidade();
    		IEnumerator v_Enumerator = v_Data.GetEnumerator();
    		while (v_Enumerator.MoveNext())
    		{
    			v_ReturnList.Add((new CidadeDTOAssembler()).Create((Cidade)v_Enumerator.Current, null, null));
    		}
    		return v_ReturnList;
    	}
    
    	private static CidadeModel CreateModel(Cidade v_Data)
        {
            return (CidadeModel) (new BLL.CidadeBLL(v_Data)).getModelComplete();
        }
    
    	public static void DeleteCidade(int p_Identifier)
    	{
    		Cidade.DeleteCidade(p_Identifier);
    	}
    
    	public static void CreateCidade(CidadeModel p_Model)
    	{
    		DAL.Cidade.Create(p_Model);
    	}
    
    	public static void EditCidade(CidadeModel p_Model)
    	{
    		DAL.Cidade.Edit(p_Model);
    	}
    }
}
