//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

using DAL;
using Model;
using BLL.DTOAssembler;
using BLL.DTOQuery;

namespace BLL
{
    public partial class LoginBLL : BaseBLL
    {
    	DAL.Login m_Data;
    
    	public LoginBLL(DAL.Login p_Data)
    	{
    		this.m_Data = p_Data;
    	}
    
    	public override Model.BaseModel getModel()
    	{
    		if(this.m_Data == null)
    			return null;
    
    		Model.LoginModel v_Return = new Model.LoginModel();
    				v_Return.Id = this.m_Data.Id;
    		v_Return.Password = this.m_Data.Password;
    		v_Return.Email = this.m_Data.Email;
    		v_Return.ComboboxText = this.m_Data.ComboboxText;
    		return v_Return;
    	}
    
    	public Model.LoginModel getModelComplete()
    	{
    		Model.LoginModel v_Return = (Model.LoginModel) getModel();
    		if(v_Return == null)
    			return null;
    
    		v_Return.Perfil = getPerfil();
    		return v_Return;
    	}
    
    	internal PerfilModel getPerfil()
    	{
    		PerfilModel v_Model = new PerfilModel();
    		if (v_Model != null && m_Data != null && m_Data.Perfil!= null)
    		{
    			v_Model = (PerfilModel)(new BLL.PerfilBLL(m_Data.Perfil).getModel());
    		}
    		return v_Model;
    	}
    	public static LoginModel GetLogin(int p_Identifier)
    	{
    		Login v_Data = Login.GetLogin(p_Identifier);
            return  ( LoginModel)(new BLL.LoginBLL(v_Data).getModelComplete());
    	}
    
    	public static LoginModel GetLogin(int p_Identifier, LoginDTOQuery p_Query)
    	{
    		Login v_Data = Login.GetLogin(p_Identifier);
    		return (new LoginDTOAssembler()).Create(v_Data, null, p_Query);
    	}
    
    	public static ICollection<LoginModel> ListLogin()
    	{
    		ICollection<LoginModel> v_ReturnList = new Collection<LoginModel>();
    		ICollection<Login> v_Data = Login.ListLogin();
    		IEnumerator v_Enumerator = v_Data.GetEnumerator();
    		while (v_Enumerator.MoveNext())
    		{
    			v_ReturnList.Add((new LoginDTOAssembler()).Create((Login)v_Enumerator.Current, null, null));
    		}
    		return v_ReturnList;
    	}
    
    	private static LoginModel CreateModel(Login v_Data)
        {
            return (LoginModel) (new BLL.LoginBLL(v_Data)).getModelComplete();
        }
    
    	public static void DeleteLogin(int p_Identifier)
    	{
    		Login.DeleteLogin(p_Identifier);
    	}
    
    	public static void CreateLogin(LoginModel p_Model)
    	{
    		DAL.Login.Create(p_Model);
    	}
    
    	public static void EditLogin(LoginModel p_Model)
    	{
    		DAL.Login.Edit(p_Model);
    	}
    }
}
