//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

using DAL;
using Model;
using BLL.DTOAssembler;
using BLL.DTOQuery;

namespace BLL
{
    public partial class PerfilBLL : BaseBLL
    {
    	DAL.Perfil m_Data;
    
    	public PerfilBLL(DAL.Perfil p_Data)
    	{
    		this.m_Data = p_Data;
    	}
    
    	public override Model.BaseModel getModel()
    	{
    		if(this.m_Data == null)
    			return null;
    
    		Model.PerfilModel v_Return = new Model.PerfilModel();
    				v_Return.Id = this.m_Data.Id;
    		v_Return.Name = this.m_Data.Name;
    		v_Return.ComboboxText = this.m_Data.ComboboxText;
    		return v_Return;
    	}
    
    	public Model.PerfilModel getModelComplete()
    	{
    		Model.PerfilModel v_Return = (Model.PerfilModel) getModel();
    		if(v_Return == null)
    			return null;
    
    		v_Return.Login = getLogin();
    		v_Return.SubMenu = getSubMenu();
    		return v_Return;
    	}
    
    	internal List<LoginModel> getLogin()
    	{
    		List<LoginModel> v_Model = new List<LoginModel>();
    		if (v_Model != null && m_Data != null && m_Data.Login!= null)
    		{
    			//v_Model = (LoginModel)(new BLL.LoginBLL(m_Data.Login).getModel());
    		}
    		return v_Model;
    	}
    	internal List<SubMenuModel> getSubMenu()
    	{
    		List<SubMenuModel> v_Model = new List<SubMenuModel>();
    		if (v_Model != null && m_Data != null && m_Data.SubMenu!= null)
    		{
    			//v_Model = (SubMenuModel)(new BLL.SubMenuBLL(m_Data.SubMenu).getModel());
    		}
    		return v_Model;
    	}
    	public static PerfilModel GetPerfil(int p_Identifier)
    	{
    		Perfil v_Data = Perfil.GetPerfil(p_Identifier);
            return  ( PerfilModel)(new BLL.PerfilBLL(v_Data).getModelComplete());
    	}
    
    	public static PerfilModel GetPerfil(int p_Identifier, PerfilDTOQuery p_Query)
    	{
    		Perfil v_Data = Perfil.GetPerfil(p_Identifier);
    		return (new PerfilDTOAssembler()).Create(v_Data, null, p_Query);
    	}
    
    	public static ICollection<PerfilModel> ListPerfil()
    	{
    		ICollection<PerfilModel> v_ReturnList = new Collection<PerfilModel>();
    		ICollection<Perfil> v_Data = Perfil.ListPerfil();
    		IEnumerator v_Enumerator = v_Data.GetEnumerator();
    		while (v_Enumerator.MoveNext())
    		{
    			v_ReturnList.Add((new PerfilDTOAssembler()).Create((Perfil)v_Enumerator.Current, null, null));
    		}
    		return v_ReturnList;
    	}
    
    	private static PerfilModel CreateModel(Perfil v_Data)
        {
            return (PerfilModel) (new BLL.PerfilBLL(v_Data)).getModelComplete();
        }
    
    	public static void DeletePerfil(int p_Identifier)
    	{
    		Perfil.DeletePerfil(p_Identifier);
    	}
    
    	public static void CreatePerfil(PerfilModel p_Model)
    	{
    		DAL.Perfil.Create(p_Model);
    	}
    
    	public static void EditPerfil(PerfilModel p_Model)
    	{
    		DAL.Perfil.Edit(p_Model);
    	}
    }
}
