//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

using DAL;
using Model;
using BLL.DTOAssembler;
using BLL.DTOQuery;

namespace BLL
{
    public partial class SubMenuBLL : BaseBLL
    {
    	DAL.SubMenu m_Data;
    
    	public SubMenuBLL(DAL.SubMenu p_Data)
    	{
    		this.m_Data = p_Data;
    	}
    
    	public override Model.BaseModel getModel()
    	{
    		if(this.m_Data == null)
    			return null;
    
    		Model.SubMenuModel v_Return = new Model.SubMenuModel();
    				v_Return.Id = this.m_Data.Id;
    		v_Return.Name = this.m_Data.Name;
    		v_Return.Url = this.m_Data.Url;
    		v_Return.ClassName = this.m_Data.ClassName;
    		v_Return.ComboboxText = this.m_Data.ComboboxText;
    		return v_Return;
    	}
    
    	public Model.SubMenuModel getModelComplete()
    	{
    		Model.SubMenuModel v_Return = (Model.SubMenuModel) getModel();
    		if(v_Return == null)
    			return null;
    
    		v_Return.Menu = getMenu();
    		v_Return.Perfil = getPerfil();
    		return v_Return;
    	}
    
    	internal List<PerfilModel> getPerfil()
    	{
    		List<PerfilModel> v_Model = new List<PerfilModel>();
    		if (v_Model != null && m_Data != null && m_Data.Perfil!= null)
    		{
    			//v_Model = (PerfilModel)(new BLL.PerfilBLL(m_Data.Perfil).getModel());
    		}
    		return v_Model;
    	}
    	internal MenuModel getMenu()
    	{
    		MenuModel v_Model = new MenuModel();
    		if (v_Model != null && m_Data != null && m_Data.Menu!= null)
    		{
    			v_Model = (MenuModel)(new BLL.MenuBLL(m_Data.Menu).getModel());
    		}
    		return v_Model;
    	}
    	public static SubMenuModel GetSubMenu(int p_Identifier)
    	{
    		SubMenu v_Data = SubMenu.GetSubMenu(p_Identifier);
            return  ( SubMenuModel)(new BLL.SubMenuBLL(v_Data).getModelComplete());
    	}
    
    	public static SubMenuModel GetSubMenu(int p_Identifier, SubMenuDTOQuery p_Query)
    	{
    		SubMenu v_Data = SubMenu.GetSubMenu(p_Identifier);
    		return (new SubMenuDTOAssembler()).Create(v_Data, null, p_Query);
    	}
    
    	public static ICollection<SubMenuModel> ListSubMenu()
    	{
    		ICollection<SubMenuModel> v_ReturnList = new Collection<SubMenuModel>();
    		ICollection<SubMenu> v_Data = SubMenu.ListSubMenu();
    		IEnumerator v_Enumerator = v_Data.GetEnumerator();
    		while (v_Enumerator.MoveNext())
    		{
    			v_ReturnList.Add((new SubMenuDTOAssembler()).Create((SubMenu)v_Enumerator.Current, null, null));
    		}
    		return v_ReturnList;
    	}
    
    	private static SubMenuModel CreateModel(SubMenu v_Data)
        {
            return (SubMenuModel) (new BLL.SubMenuBLL(v_Data)).getModelComplete();
        }
    
    	public static void DeleteSubMenu(int p_Identifier)
    	{
    		SubMenu.DeleteSubMenu(p_Identifier);
    	}
    
    	public static void CreateSubMenu(SubMenuModel p_Model)
    	{
    		DAL.SubMenu.Create(p_Model);
    	}
    
    	public static void EditSubMenu(SubMenuModel p_Model)
    	{
    		DAL.SubMenu.Edit(p_Model);
    	}
    }
}
