//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1008
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Util
{
    using System;


    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Internationalization
    {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Internationalization()
        {
        }

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager
        {
            get
            {
                if (object.ReferenceEquals(resourceMan, null))
                {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Util.Internationalization", typeof(Internationalization).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture
        {
            get
            {
                return resourceCulture;
            }
            set
            {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Abdome.
        /// </summary>
        public static string Abdome
        {
            get
            {
                return ResourceManager.GetString("Abdome", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Abscesso parede.
        /// </summary>
        public static string AbscessoParede
        {
            get
            {
                return ResourceManager.GetString("AbscessoParede", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Ações.
        /// </summary>
        public static string Acoes
        {
            get
            {
                return ResourceManager.GetString("Acoes", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Acompanhamento médico.
        /// </summary>
        public static string AcompanhamentoMedico
        {
            get
            {
                return ResourceManager.GetString("AcompanhamentoMedico", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Acompanhante.
        /// </summary>
        public static string Acompanhante
        {
            get
            {
                return ResourceManager.GetString("Acompanhante", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Agendada.
        /// </summary>
        public static string Agendada
        {
            get
            {
                return ResourceManager.GetString("Agendada", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Água.
        /// </summary>
        public static string Agua
        {
            get
            {
                return ResourceManager.GetString("Agua", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Álcool.
        /// </summary>
        public static string Alcool
        {
            get
            {
                return ResourceManager.GetString("Alcool", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Álcool diariamente.
        /// </summary>
        public static string AlcoolDiariamente
        {
            get
            {
                return ResourceManager.GetString("AlcoolDiariamente", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Alimenta-se bem? Como é seu apetite?.
        /// </summary>
        public static string Alimentacao
        {
            get
            {
                return ResourceManager.GetString("Alimentacao", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Alimentação noturna.
        /// </summary>
        public static string AlimentacaoNoturna
        {
            get
            {
                return ResourceManager.GetString("AlimentacaoNoturna", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Alimento que mais gosta.
        /// </summary>
        public static string AlimentoGosta
        {
            get
            {
                return ResourceManager.GetString("AlimentoGosta", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Alimento que não gosta.
        /// </summary>
        public static string AlimentoNaoGosta
        {
            get
            {
                return ResourceManager.GetString("AlimentoNaoGosta", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Alterações gástricas.
        /// </summary>
        public static string AlteracoesGastricas
        {
            get
            {
                return ResourceManager.GetString("AlteracoesGastricas", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Altura.
        /// </summary>
        public static string Altura
        {
            get
            {
                return ResourceManager.GetString("Altura", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Ansiedade.
        /// </summary>
        public static string Ansiedade
        {
            get
            {
                return ResourceManager.GetString("Ansiedade", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Antecedentes cirúgicos.
        /// </summary>
        public static string AntecedentesCirurgicos
        {
            get
            {
                return ResourceManager.GetString("AntecedentesCirurgicos", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Antecedentes familiares.
        /// </summary>
        public static string AntecedentesFamiliares
        {
            get
            {
                return ResourceManager.GetString("AntecedentesFamiliares", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Antecedentes patológicos.
        /// </summary>
        public static string AntecedentesPatologicos
        {
            get
            {
                return ResourceManager.GetString("AntecedentesPatologicos", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Apneia.
        /// </summary>
        public static string Apneia
        {
            get
            {
                return ResourceManager.GetString("Apneia", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Arritmias.
        /// </summary>
        public static string Arritmias
        {
            get
            {
                return ResourceManager.GetString("Arritmias", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Artroses nos joelhos.
        /// </summary>
        public static string ArtrosesJoelhos
        {
            get
            {
                return ResourceManager.GetString("ArtrosesJoelhos", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Artroses nos tornozelos.
        /// </summary>
        public static string ArtrosesTornozelos
        {
            get
            {
                return ResourceManager.GetString("ArtrosesTornozelos", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to ASA.
        /// </summary>
        public static string ASA
        {
            get
            {
                return ResourceManager.GetString("ASA", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Asma.
        /// </summary>
        public static string Asma
        {
            get
            {
                return ResourceManager.GetString("Asma", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Atelectasia.
        /// </summary>
        public static string Atelectasia
        {
            get
            {
                return ResourceManager.GetString("Atelectasia", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Atividade física.
        /// </summary>
        public static string AtividadeFisica
        {
            get
            {
                return ResourceManager.GetString("AtividadeFisica", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Os pais ajudam o pacienta nas atividades escolares?.
        /// </summary>
        public static string AuxilioPaisNaEscola
        {
            get
            {
                return ResourceManager.GetString("AuxilioPaisNaEscola", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Avaliação anestesiológica.
        /// </summary>
        public static string AvaliacaoAnestesiologica
        {
            get
            {
                return ResourceManager.GetString("AvaliacaoAnestesiologica", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Availiação cardiológica.
        /// </summary>
        public static string AvaliacaoCardiologica
        {
            get
            {
                return ResourceManager.GetString("AvaliacaoCardiologica", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Avaliação endocrinológica.
        /// </summary>
        public static string AvaliacaoEndocrinologica
        {
            get
            {
                return ResourceManager.GetString("AvaliacaoEndocrinologica", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Avaliação fisioterápica.
        /// </summary>
        public static string AvaliacaoFisioterapica
        {
            get
            {
                return ResourceManager.GetString("AvaliacaoFisioterapica", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Avaliação nutricional.
        /// </summary>
        public static string AvaliacaoNutricional
        {
            get
            {
                return ResourceManager.GetString("AvaliacaoNutricional", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Avaliação pneumológica.
        /// </summary>
        public static string AvaliacaoPneumologica
        {
            get
            {
                return ResourceManager.GetString("AvaliacaoPneumologica", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Avaliação psicológica.
        /// </summary>
        public static string AvaliacaoPsicologica
        {
            get
            {
                return ResourceManager.GetString("AvaliacaoPsicologica", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to AVC.
        /// </summary>
        public static string AVC
        {
            get
            {
                return ResourceManager.GetString("AVC", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Bronquite/Asma.
        /// </summary>
        public static string BronquiteAsma
        {
            get
            {
                return ResourceManager.GetString("BronquiteAsma", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Procurar.
        /// </summary>
        public static string Buscar
        {
            get
            {
                return ResourceManager.GetString("Buscar", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Calorias.
        /// </summary>
        public static string Calorias
        {
            get
            {
                return ResourceManager.GetString("Calorias", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Arquivo.
        /// </summary>
        public static string CaminhoImagem
        {
            get
            {
                return ResourceManager.GetString("CaminhoImagem", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Cancelar.
        /// </summary>
        public static string Cancel
        {
            get
            {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Carne gorda.
        /// </summary>
        public static string CarneGorda
        {
            get
            {
                return ResourceManager.GetString("CarneGorda", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Carotídeo.
        /// </summary>
        public static string Carotideo
        {
            get
            {
                return ResourceManager.GetString("Carotideo", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Categoria do exame.
        /// </summary>
        public static string CategoriaExame
        {
            get
            {
                return ResourceManager.GetString("CategoriaExame", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Cateter Peridural.
        /// </summary>
        public static string CateterPeridural
        {
            get
            {
                return ResourceManager.GetString("CateterPeridural", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Celular.
        /// </summary>
        public static string Celular
        {
            get
            {
                return ResourceManager.GetString("Celular", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Cidade.
        /// </summary>
        public static string Cidade
        {
            get
            {
                return ResourceManager.GetString("Cidade", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Circunferência do braço.
        /// </summary>
        public static string CircunferenciaBraco
        {
            get
            {
                return ResourceManager.GetString("CircunferenciaBraco", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Circunferência da cintura.
        /// </summary>
        public static string CircunferenciaCintura
        {
            get
            {
                return ResourceManager.GetString("CircunferenciaCintura", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Circunferência do quadrl.
        /// </summary>
        public static string CircunferenciaQuadril
        {
            get
            {
                return ResourceManager.GetString("CircunferenciaQuadril", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Cirurgia proposta.
        /// </summary>
        public static string CirurgiaProposta
        {
            get
            {
                return ResourceManager.GetString("CirurgiaProposta", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Cirurgias associadas.
        /// </summary>
        public static string CirurgiasAssociadas
        {
            get
            {
                return ResourceManager.GetString("CirurgiasAssociadas", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Cirurgias realizadas.
        /// </summary>
        public static string CirurgiasRealizadas
        {
            get
            {
                return ResourceManager.GetString("CirurgiasRealizadas", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Classificação.
        /// </summary>
        public static string Classificacao
        {
            get
            {
                return ResourceManager.GetString("Classificacao", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Classificação de obesidade.
        /// </summary>
        public static string ClassificacaoObesidade
        {
            get
            {
                return ResourceManager.GetString("ClassificacaoObesidade", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Claudicacao.
        /// </summary>
        public static string Claudicacao
        {
            get
            {
                return ResourceManager.GetString("Claudicacao", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Colelitiase.
        /// </summary>
        public static string Colelitiase
        {
            get
            {
                return ResourceManager.GetString("Colelitiase", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Como é o fim de semana.
        /// </summary>
        public static string ComoEFimSemana
        {
            get
            {
                return ResourceManager.GetString("ComoEFimSemana", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Como reage quando é contrariado?.
        /// </summary>
        public static string ComoReageAoSerContrariado
        {
            get
            {
                return ResourceManager.GetString("ComoReageAoSerContrariado", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Complicações cirúrgicas.
        /// </summary>
        public static string ComplicacoesCirurgicas
        {
            get
            {
                return ResourceManager.GetString("ComplicacoesCirurgicas", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Complicações clínicas.
        /// </summary>
        public static string ComplicacoesClinicas
        {
            get
            {
                return ResourceManager.GetString("ComplicacoesClinicas", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Compulsão alimentar.
        /// </summary>
        public static string CompulsaoAlimentar
        {
            get
            {
                return ResourceManager.GetString("CompulsaoAlimentar", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Quais as condições de saúde da mãe durante a gravidez?.
        /// </summary>
        public static string CondicaoSaudeMaeNaGravidez
        {
            get
            {
                return ResourceManager.GetString("CondicaoSaudeMaeNaGravidez", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Quais as condições emocionais da mãe durante a gravidez?.
        /// </summary>
        public static string CondicoesEmocionaisMaeNaGravidez
        {
            get
            {
                return ResourceManager.GetString("CondicoesEmocionaisMaeNaGravidez", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Conduta nutricional.
        /// </summary>
        public static string CondutaNutricional
        {
            get
            {
                return ResourceManager.GetString("CondutaNutricional", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Considerações.
        /// </summary>
        public static string Consideracoes
        {
            get
            {
                return ResourceManager.GetString("Consideracoes", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Contra-indicação.
        /// </summary>
        public static string ContraIndicacao
        {
            get
            {
                return ResourceManager.GetString("ContraIndicacao", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Convênio.
        /// </summary>
        public static string Convenio
        {
            get
            {
                return ResourceManager.GetString("Convenio", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Coração.
        /// </summary>
        public static string Coracao
        {
            get
            {
                return ResourceManager.GetString("Coracao", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Coronariopatia.
        /// </summary>
        public static string Coronariopatia
        {
            get
            {
                return ResourceManager.GetString("Coronariopatia", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to CPF.
        /// </summary>
        public static string CPF
        {
            get
            {
                return ResourceManager.GetString("CPF", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Criar.
        /// </summary>
        public static string Create
        {
            get
            {
                return ResourceManager.GetString("Create", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to CRM.
        /// </summary>
        public static string CRM
        {
            get
            {
                return ResourceManager.GetString("CRM", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Data.
        /// </summary>
        public static string Data
        {
            get
            {
                return ResourceManager.GetString("Data", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Data do Acompanhamento.
        /// </summary>
        public static string DataAcompanhamento
        {
            get
            {
                return ResourceManager.GetString("DataAcompanhamento", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Data de Agendamento.
        /// </summary>
        public static string DataAgendamento
        {
            get
            {
                return ResourceManager.GetString("DataAgendamento", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Data da alta do hospital.
        /// </summary>
        public static string DataAlta
        {
            get
            {
                return ResourceManager.GetString("DataAlta", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Data da Cirurgia.
        /// </summary>
        public static string DataCirurgia
        {
            get
            {
                return ResourceManager.GetString("DataCirurgia", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Data da Consulta.
        /// </summary>
        public static string DataConsulta
        {
            get
            {
                return ResourceManager.GetString("DataConsulta", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Data do Exame.
        /// </summary>
        public static string DataExame
        {
            get
            {
                return ResourceManager.GetString("DataExame", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Data de medição.
        /// </summary>
        public static string DataMedicao
        {
            get
            {
                return ResourceManager.GetString("DataMedicao", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Data de Nascimento.
        /// </summary>
        public static string DataNascimento
        {
            get
            {
                return ResourceManager.GetString("DataNascimento", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Decubito dorsal.
        /// </summary>
        public static string DecubitoDorsal
        {
            get
            {
                return ResourceManager.GetString("DecubitoDorsal", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Deiscencia parede.
        /// </summary>
        public static string DeiscenciaParede
        {
            get
            {
                return ResourceManager.GetString("DeiscenciaParede", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Remover.
        /// </summary>
        public static string Delete
        {
            get
            {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Depressão.
        /// </summary>
        public static string Depressao
        {
            get
            {
                return ResourceManager.GetString("Depressao", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Descrição.
        /// </summary>
        public static string Descricao
        {
            get
            {
                return ResourceManager.GetString("Descricao", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Andou com que idade? É lento para realizar alguma atividade?.
        /// </summary>
        public static string Desenvolvimento
        {
            get
            {
                return ResourceManager.GetString("Desenvolvimento", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Já desmaiou alguma vez?.
        /// </summary>
        public static string DesmaiouAlgumaVez
        {
            get
            {
                return ResourceManager.GetString("DesmaiouAlgumaVez", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Diabetes.
        /// </summary>
        public static string Diabetes
        {
            get
            {
                return ResourceManager.GetString("Diabetes", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Diarréia.
        /// </summary>
        public static string Diarreia
        {
            get
            {
                return ResourceManager.GetString("Diarreia", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Dieta.
        /// </summary>
        public static string Dieta
        {
            get
            {
                return ResourceManager.GetString("Dieta", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Dismenorreia.
        /// </summary>
        public static string Dismenorreia
        {
            get
            {
                return ResourceManager.GetString("Dismenorreia", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Dispneia.
        /// </summary>
        public static string Dispneia
        {
            get
            {
                return ResourceManager.GetString("Dispneia", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Doces ou chocolates.
        /// </summary>
        public static string DocesChocolates
        {
            get
            {
                return ResourceManager.GetString("DocesChocolates", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Doença hemorroidária.
        /// </summary>
        public static string DoencaHemorroidaria
        {
            get
            {
                return ResourceManager.GetString("DoencaHemorroidaria", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Doppler MMII.
        /// </summary>
        public static string DopplerMMII
        {
            get
            {
                return ResourceManager.GetString("DopplerMMII", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Dor abdominal.
        /// </summary>
        public static string DorAbdominal
        {
            get
            {
                return ResourceManager.GetString("DorAbdominal", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Apresenta dor de cabeça?.
        /// </summary>
        public static string DorCabeca
        {
            get
            {
                return ResourceManager.GetString("DorCabeca", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Dor nos ombros/costas.
        /// </summary>
        public static string DorOmbrosCostas
        {
            get
            {
                return ResourceManager.GetString("DorOmbrosCostas", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to DRGE.
        /// </summary>
        public static string DRGE
        {
            get
            {
                return ResourceManager.GetString("DRGE", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Duração da Cirurgia.
        /// </summary>
        public static string DuracaoCirurgia
        {
            get
            {
                return ResourceManager.GetString("DuracaoCirurgia", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to ECG.
        /// </summary>
        public static string ECG
        {
            get
            {
                return ResourceManager.GetString("ECG", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Edema membros.
        /// </summary>
        public static string EdemaMembros
        {
            get
            {
                return ResourceManager.GetString("EdemaMembros", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Editar.
        /// </summary>
        public static string Edit
        {
            get
            {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Editar/Remover.
        /// </summary>
        public static string EditarOuRemover
        {
            get
            {
                return ResourceManager.GetString("EditarOuRemover", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Efeitos colaterais.
        /// </summary>
        public static string EfeitosColaterais
        {
            get
            {
                return ResourceManager.GetString("EfeitosColaterais", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to E-mail.
        /// </summary>
        public static string Email
        {
            get
            {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Endereço.
        /// </summary>
        public static string Endereco
        {
            get
            {
                return ResourceManager.GetString("Endereco", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Endoscopia digestiva alta.
        /// </summary>
        public static string EndoscopiaDigestivaAlta
        {
            get
            {
                return ResourceManager.GetString("EndoscopiaDigestivaAlta", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Episódio determinante para obesidade.
        /// </summary>
        public static string EpisodioDeterminante
        {
            get
            {
                return ResourceManager.GetString("EpisodioDeterminante", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Ereto.
        /// </summary>
        public static string Ereto
        {
            get
            {
                return ResourceManager.GetString("Ereto", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Especialidade.
        /// </summary>
        public static string Especialidade
        {
            get
            {
                return ResourceManager.GetString("Especialidade", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Estado Civil.
        /// </summary>
        public static string EstadoCivil
        {
            get
            {
                return ResourceManager.GetString("EstadoCivil", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Esterilidade.
        /// </summary>
        public static string Esterilidade
        {
            get
            {
                return ResourceManager.GetString("Esterilidade", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Etilista.
        /// </summary>
        public static string Etilista
        {
            get
            {
                return ResourceManager.GetString("Etilista", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Evisceração.
        /// </summary>
        public static string Evisceracao
        {
            get
            {
                return ResourceManager.GetString("Evisceracao", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Exame físico.
        /// </summary>
        public static string ExameFisico
        {
            get
            {
                return ResourceManager.GetString("ExameFisico", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Atualmente, faz algum tratamento médico?.
        /// </summary>
        public static string FazTratamentoMedico
        {
            get
            {
                return ResourceManager.GetString("FazTratamentoMedico", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Faz uso de substâncias psicoativas.
        /// </summary>
        public static string FazUsoSubstanciaPsicoativa
        {
            get
            {
                return ResourceManager.GetString("FazUsoSubstanciaPsicoativa", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Febre.
        /// </summary>
        public static string Febre
        {
            get
            {
                return ResourceManager.GetString("Febre", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Femural.
        /// </summary>
        public static string Femural
        {
            get
            {
                return ResourceManager.GetString("Femural", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Fistula.
        /// </summary>
        public static string Fistula
        {
            get
            {
                return ResourceManager.GetString("Fistula", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Já procuraram especialitas?.
        /// </summary>
        public static string FoiConsultadoEspecialistas
        {
            get
            {
                return ResourceManager.GetString("FoiConsultadoEspecialistas", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Foto.
        /// </summary>
        public static string Foto
        {
            get
            {
                return ResourceManager.GetString("Foto", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Frituras.
        /// </summary>
        public static string Frituras
        {
            get
            {
                return ResourceManager.GetString("Frituras", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Frutas.
        /// </summary>
        public static string Frutas
        {
            get
            {
                return ResourceManager.GetString("Frutas", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Fumo.
        /// </summary>
        public static string Fumo
        {
            get
            {
                return ResourceManager.GetString("Fumo", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Função intestinal.
        /// </summary>
        public static string FuncaoIntestinal
        {
            get
            {
                return ResourceManager.GetString("FuncaoIntestinal", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Gestações.
        /// </summary>
        public static string Gestacoes
        {
            get
            {
                return ResourceManager.GetString("Gestacoes", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Goldman.
        /// </summary>
        public static string Goldman
        {
            get
            {
                return ResourceManager.GetString("Goldman", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Gosta de estudar?.
        /// </summary>
        public static string GostaEstudar
        {
            get
            {
                return ResourceManager.GetString("GostaEstudar", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to O paciente gosta de ir à escola?.
        /// </summary>
        public static string GostaIrEscola
        {
            get
            {
                return ResourceManager.GetString("GostaIrEscola", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Gota.
        /// </summary>
        public static string Gota
        {
            get
            {
                return ResourceManager.GetString("Gota", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Grau de Instrução.
        /// </summary>
        public static string GrauInstrucao
        {
            get
            {
                return ResourceManager.GetString("GrauInstrucao", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Grau de parentesco do acompanhante.
        /// </summary>
        public static string GrauParentescoAcompanhante
        {
            get
            {
                return ResourceManager.GetString("GrauParentescoAcompanhante", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Hábitos alimentares.
        /// </summary>
        public static string HabitosAlimentares
        {
            get
            {
                return ResourceManager.GetString("HabitosAlimentares", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Hábito de vida.
        /// </summary>
        public static string HabitosVida
        {
            get
            {
                return ResourceManager.GetString("HabitosVida", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to HAS.
        /// </summary>
        public static string HAS
        {
            get
            {
                return ResourceManager.GetString("HAS", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Caso de hipertensão familiar.
        /// </summary>
        public static string HipertensaoFamilia
        {
            get
            {
                return ResourceManager.GetString("HipertensaoFamilia", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Hipertensão familiar.
        /// </summary>
        public static string HipertensaoFamiliar
        {
            get
            {
                return ResourceManager.GetString("HipertensaoFamiliar", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Hipertiroidismo.
        /// </summary>
        public static string Hipertiroidismo
        {
            get
            {
                return ResourceManager.GetString("Hipertiroidismo", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Hipoteses diagnosticadas.
        /// </summary>
        public static string HipotesesDiagnosticadas
        {
            get
            {
                return ResourceManager.GetString("HipotesesDiagnosticadas", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Hipotireoidismo.
        /// </summary>
        public static string HipoTireoidismo
        {
            get
            {
                return ResourceManager.GetString("HipoTireoidismo", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Hirsutismo.
        /// </summary>
        public static string Hirsutismo
        {
            get
            {
                return ResourceManager.GetString("Hirsutismo", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to História da moléstia atual.
        /// </summary>
        public static string HistoriaMolestiaAtual
        {
            get
            {
                return ResourceManager.GetString("HistoriaMolestiaAtual", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Histórico de patologias na família.
        /// </summary>
        public static string HistoricoPatologiasFamilia
        {
            get
            {
                return ResourceManager.GetString("HistoricoPatologiasFamilia", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Hora de Início.
        /// </summary>
        public static string HoraInicio
        {
            get
            {
                return ResourceManager.GetString("HoraInicio", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Horário.
        /// </summary>
        public static string Horario
        {
            get
            {
                return ResourceManager.GetString("Horario", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Tem horário para estudar?.
        /// </summary>
        public static string HorarioEstudar
        {
            get
            {
                return ResourceManager.GetString("HorarioEstudar", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Id.
        /// </summary>
        public static string Id
        {
            get
            {
                return ResourceManager.GetString("Id", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Imagem.
        /// </summary>
        public static string Imagem
        {
            get
            {
                return ResourceManager.GetString("Imagem", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to IMC.
        /// </summary>
        public static string IMC
        {
            get
            {
                return ResourceManager.GetString("IMC", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Impotência sexual.
        /// </summary>
        public static string ImpotenciaSexual
        {
            get
            {
                return ResourceManager.GetString("ImpotenciaSexual", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Indicação.
        /// </summary>
        public static string Indicacao
        {
            get
            {
                return ResourceManager.GetString("Indicacao", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to IndiciosHASecundaria.
        /// </summary>
        public static string IndiciosHASecundaria
        {
            get
            {
                return ResourceManager.GetString("IndiciosHASecundaria", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Infarto do miocárdio.
        /// </summary>
        public static string InfartoMiocardio
        {
            get
            {
                return ResourceManager.GetString("InfartoMiocardio", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Insônia.
        /// </summary>
        public static string Insonia
        {
            get
            {
                return ResourceManager.GetString("Insonia", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Insuficiência cardíaca.
        /// </summary>
        public static string InsuficienciaCardiaca
        {
            get
            {
                return ResourceManager.GetString("InsuficienciaCardiaca", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Intercorrências anestésicas.
        /// </summary>
        public static string IntercorrenciasAnestesicas
        {
            get
            {
                return ResourceManager.GetString("IntercorrenciasAnestesicas", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Intercorrências cirúrgicas.
        /// </summary>
        public static string IntercorrenciasCirurgicas
        {
            get
            {
                return ResourceManager.GetString("IntercorrenciasCirurgicas", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Intercorrências pós operatórias.
        /// </summary>
        public static string IntercorrenciasPos
        {
            get
            {
                return ResourceManager.GetString("IntercorrenciasPos", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Internação em SPA?.
        /// </summary>
        public static string InternacaoSPA
        {
            get
            {
                return ResourceManager.GetString("InternacaoSPA", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Internações SPA.
        /// </summary>
        public static string InternacoesSPA
        {
            get
            {
                return ResourceManager.GetString("InternacoesSPA", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Intolerâncias.
        /// </summary>
        public static string Intolerancias
        {
            get
            {
                return ResourceManager.GetString("Intolerancias", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Laudo.
        /// </summary>
        public static string Laudo
        {
            get
            {
                return ResourceManager.GetString("Laudo", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Lee.
        /// </summary>
        public static string Lee
        {
            get
            {
                return ResourceManager.GetString("Lee", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Legumes.
        /// </summary>
        public static string Legumes
        {
            get
            {
                return ResourceManager.GetString("Legumes", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Leite e derivados.
        /// </summary>
        public static string LeiteDerivados
        {
            get
            {
                return ResourceManager.GetString("LeiteDerivados", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Levou alguma queda ou susto forte?.
        /// </summary>
        public static string LevouQuedaOuSusto
        {
            get
            {
                return ResourceManager.GetString("LevouQuedaOuSusto", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Link.
        /// </summary>
        public static string Link
        {
            get
            {
                return ResourceManager.GetString("Link", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string Login
        {
            get
            {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Massa.
        /// </summary>
        public static string Massa
        {
            get
            {
                return ResourceManager.GetString("Massa", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Medicação.
        /// </summary>
        public static string Medicacao
        {
            get
            {
                return ResourceManager.GetString("Medicacao", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Medicação atual.
        /// </summary>
        public static string MedicacaoAtual
        {
            get
            {
                return ResourceManager.GetString("MedicacaoAtual", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Medicações em uso.
        /// </summary>
        public static string MedicacaoEmUso
        {
            get
            {
                return ResourceManager.GetString("MedicacaoEmUso", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Medição.
        /// </summary>
        public static string Medicao
        {
            get
            {
                return ResourceManager.GetString("Medicao", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Profissional.
        /// </summary>
        public static string Medico
        {
            get
            {
                return ResourceManager.GetString("Medico", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Medidas do paciente.
        /// </summary>
        public static string MedidaPaciente
        {
            get
            {
                return ResourceManager.GetString("MedidaPaciente", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Melena.
        /// </summary>
        public static string Melena
        {
            get
            {
                return ResourceManager.GetString("Melena", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Motivo.
        /// </summary>
        public static string Motivo
        {
            get
            {
                return ResourceManager.GetString("Motivo", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Motivo da consulta.
        /// </summary>
        public static string MotivoConsulta
        {
            get
            {
                return ResourceManager.GetString("MotivoConsulta", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Motivo do insucesso do tratamento.
        /// </summary>
        public static string MotivoInsucesso
        {
            get
            {
                return ResourceManager.GetString("MotivoInsucesso", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Motivo da UTI no pós-operatório.
        /// </summary>
        public static string MotivoUTIPosOperatorio
        {
            get
            {
                return ResourceManager.GetString("MotivoUTIPosOperatorio", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to MSD.
        /// </summary>
        public static string MSD
        {
            get
            {
                return ResourceManager.GetString("MSD", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to MSE.
        /// </summary>
        public static string MSE
        {
            get
            {
                return ResourceManager.GetString("MSE", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Nefropatia.
        /// </summary>
        public static string Nefropatia
        {
            get
            {
                return ResourceManager.GetString("Nefropatia", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Novo.
        /// </summary>
        public static string New
        {
            get
            {
                return ResourceManager.GetString("New", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Nome.
        /// </summary>
        public static string Nome
        {
            get
            {
                return ResourceManager.GetString("Nome", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Nome da mãe.
        /// </summary>
        public static string NomeMae
        {
            get
            {
                return ResourceManager.GetString("NomeMae", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Nome do Médico.
        /// </summary>
        public static string NomeMedico
        {
            get
            {
                return ResourceManager.GetString("NomeMedico", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Nome do Paciente.
        /// </summary>
        public static string NomePaciente
        {
            get
            {
                return ResourceManager.GetString("NomePaciente", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Nome do pai.
        /// </summary>
        public static string NomePai
        {
            get
            {
                return ResourceManager.GetString("NomePai", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Número de tentativas de tratamento.
        /// </summary>
        public static string NumeroTentativasTratamento
        {
            get
            {
                return ResourceManager.GetString("NumeroTentativasTratamento", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Óbitos na família.
        /// </summary>
        public static string ObitosFamilia
        {
            get
            {
                return ResourceManager.GetString("ObitosFamilia", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Objetivo do tratamento.
        /// </summary>
        public static string ObjetivoTratamento
        {
            get
            {
                return ResourceManager.GetString("ObjetivoTratamento", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Observações.
        /// </summary>
        public static string Observacoes
        {
            get
            {
                return ResourceManager.GetString("Observacoes", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Oleo.
        /// </summary>
        public static string Oleo
        {
            get
            {
                return ResourceManager.GetString("Oleo", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Paciente.
        /// </summary>
        public static string Paciente
        {
            get
            {
                return ResourceManager.GetString("Paciente", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Parentes obesos.
        /// </summary>
        public static string ParentesObesos
        {
            get
            {
                return ResourceManager.GetString("ParentesObesos", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Senha.
        /// </summary>
        public static string Password
        {
            get
            {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Histórico de patologias na família.
        /// </summary>
        public static string PatologiasDosAntecedentes
        {
            get
            {
                return ResourceManager.GetString("PatologiasDosAntecedentes", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Patologias na coluna.
        /// </summary>
        public static string PatologiasNaColuna
        {
            get
            {
                return ResourceManager.GetString("PatologiasNaColuna", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Pedioso.
        /// </summary>
        public static string Pedioso
        {
            get
            {
                return ResourceManager.GetString("Pedioso", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Peritonite.
        /// </summary>
        public static string Peritonite
        {
            get
            {
                return ResourceManager.GetString("Peritonite", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Peso.
        /// </summary>
        public static string Peso
        {
            get
            {
                return ResourceManager.GetString("Peso", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Peso no dia da alta.
        /// </summary>
        public static string PesoAlta
        {
            get
            {
                return ResourceManager.GetString("PesoAlta", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Peso do paciente(Após alta do hospital).
        /// </summary>
        public static string PesoAltaHospitalar
        {
            get
            {
                return ResourceManager.GetString("PesoAltaHospitalar", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Peso do paciente(Antes da cirurgia).
        /// </summary>
        public static string PesoAntesCirurgia
        {
            get
            {
                return ResourceManager.GetString("PesoAntesCirurgia", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Peso máximo.
        /// </summary>
        public static string PesoMaximo
        {
            get
            {
                return ResourceManager.GetString("PesoMaximo", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Peso mínimo.
        /// </summary>
        public static string PesoMinimo
        {
            get
            {
                return ResourceManager.GetString("PesoMinimo", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Peso na data de alta.
        /// </summary>
        public static string PesoNaAlta
        {
            get
            {
                return ResourceManager.GetString("PesoNaAlta", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Peso na data da cirurgia.
        /// </summary>
        public static string PesoNaCirurgia
        {
            get
            {
                return ResourceManager.GetString("PesoNaCirurgia", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Pílula anticoncepcional.
        /// </summary>
        public static string PilulaAnticoncepcional
        {
            get
            {
                return ResourceManager.GetString("PilulaAnticoncepcional", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Plano propedêutico.
        /// </summary>
        public static string PlanoPropedeutico
        {
            get
            {
                return ResourceManager.GetString("PlanoPropedeutico", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Pneumonia.
        /// </summary>
        public static string Pneumonia
        {
            get
            {
                return ResourceManager.GetString("Pneumonia", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to % Gordura.
        /// </summary>
        public static string PorcentagemGordura
        {
            get
            {
                return ResourceManager.GetString("PorcentagemGordura", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to % Gordura visceral.
        /// </summary>
        public static string PorcentagemGorduraVisceraol
        {
            get
            {
                return ResourceManager.GetString("PorcentagemGorduraVisceraol", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to % Muscular.
        /// </summary>
        public static string PorcentagemMuscular
        {
            get
            {
                return ResourceManager.GetString("PorcentagemMuscular", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Pressão arterial.
        /// </summary>
        public static string PressaoArterial
        {
            get
            {
                return ResourceManager.GetString("PressaoArterial", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Primeira meta.
        /// </summary>
        public static string PrimeiraMeta
        {
            get
            {
                return ResourceManager.GetString("PrimeiraMeta", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Apresenta algum problema de audição?.
        /// </summary>
        public static string ProblemaAudicao
        {
            get
            {
                return ResourceManager.GetString("ProblemaAudicao", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Algum parente apresenta problemas relacionados à desmaios, convulsões ou ataques?.
        /// </summary>
        public static string ProblemasFamilia
        {
            get
            {
                return ResourceManager.GetString("ProblemasFamilia", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Teve algum problema após o parto?.
        /// </summary>
        public static string ProblemasPosParto
        {
            get
            {
                return ResourceManager.GetString("ProblemasPosParto", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Apresenta problema de visão?.
        /// </summary>
        public static string ProblemaVisao
        {
            get
            {
                return ResourceManager.GetString("ProblemaVisao", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Profissão.
        /// </summary>
        public static string Profissao
        {
            get
            {
                return ResourceManager.GetString("Profissao", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Valor inválido.
        /// </summary>
        public static string PropertyValueInvalid
        {
            get
            {
                return ResourceManager.GetString("PropertyValueInvalid", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Pulmões.
        /// </summary>
        public static string Pulmoes
        {
            get
            {
                return ResourceManager.GetString("Pulmoes", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Quais as atividades preferidas?.
        /// </summary>
        public static string QuaisAsAtividadesPreferidas
        {
            get
            {
                return ResourceManager.GetString("QuaisAsAtividadesPreferidas", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Quais as medidas usadas para disciplinar o paciente?.
        /// </summary>
        public static string QuaisMedidasParaDisciplinar
        {
            get
            {
                return ResourceManager.GetString("QuaisMedidasParaDisciplinar", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Qual a queixa atual?.
        /// </summary>
        public static string QueixaAtual
        {
            get
            {
                return ResourceManager.GetString("QueixaAtual", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Queixa principal.
        /// </summary>
        public static string QueixaPrincipal
        {
            get
            {
                return ResourceManager.GetString("QueixaPrincipal", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Quitandas.
        /// </summary>
        public static string Quitandas
        {
            get
            {
                return ResourceManager.GetString("Quitandas", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Radial.
        /// </summary>
        public static string Radial
        {
            get
            {
                return ResourceManager.GetString("Radial", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Radiografia torax.
        /// </summary>
        public static string RadiografiaTorax
        {
            get
            {
                return ResourceManager.GetString("RadiografiaTorax", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Raio-X.
        /// </summary>
        public static string RaioxTorax
        {
            get
            {
                return ResourceManager.GetString("RaioxTorax", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Realizada.
        /// </summary>
        public static string Realizada
        {
            get
            {
                return ResourceManager.GetString("Realizada", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Realizado.
        /// </summary>
        public static string Realizado
        {
            get
            {
                return ResourceManager.GetString("Realizado", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Refrigerante.
        /// </summary>
        public static string Refrigerante
        {
            get
            {
                return ResourceManager.GetString("Refrigerante", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Remover.
        /// </summary>
        public static string Remover
        {
            get
            {
                return ResourceManager.GetString("Remover", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Reoperação.
        /// </summary>
        public static string Reoperacao
        {
            get
            {
                return ResourceManager.GetString("Reoperacao", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Já repetiu a série alguma vez?.
        /// </summary>
        public static string RepetiuSerieAlgumaVez
        {
            get
            {
                return ResourceManager.GetString("RepetiuSerieAlgumaVez", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Este campo é obrigatório.
        /// </summary>
        public static string Required
        {
            get
            {
                return ResourceManager.GetString("Required", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Retorno.
        /// </summary>
        public static string Retorno
        {
            get
            {
                return ResourceManager.GetString("Retorno", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to RG.
        /// </summary>
        public static string RG
        {
            get
            {
                return ResourceManager.GetString("RG", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Rotina diária.
        /// </summary>
        public static string RotinaDiaria
        {
            get
            {
                return ResourceManager.GetString("RotinaDiaria", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Sal.
        /// </summary>
        public static string Sal
        {
            get
            {
                return ResourceManager.GetString("Sal", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Adiciona sal na comida pronta.
        /// </summary>
        public static string SalComidaPronta
        {
            get
            {
                return ResourceManager.GetString("SalComidaPronta", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Salvar.
        /// </summary>
        public static string Save
        {
            get
            {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Sentado.
        /// </summary>
        public static string Sentado
        {
            get
            {
                return ResourceManager.GetString("Sentado", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Sexo.
        /// </summary>
        public static string Sexo
        {
            get
            {
                return ResourceManager.GetString("Sexo", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Sofreu algum acidente?.
        /// </summary>
        public static string SofreuAcidente
        {
            get
            {
                return ResourceManager.GetString("SofreuAcidente", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Como é o sono? Qual horário? Dorme sozinho ou acompanhado?.
        /// </summary>
        public static string Sono
        {
            get
            {
                return ResourceManager.GetString("Sono", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Sopro abdominal.
        /// </summary>
        public static string SoproAbdominal
        {
            get
            {
                return ResourceManager.GetString("SoproAbdominal", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Submeteu-se a alguma cirurgia?.
        /// </summary>
        public static string SubmeteuCirurgia
        {
            get
            {
                return ResourceManager.GetString("SubmeteuCirurgia", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Tabagista.
        /// </summary>
        public static string Tabagista
        {
            get
            {
                return ResourceManager.GetString("Tabagista", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Telefone.
        /// </summary>
        public static string Telefone
        {
            get
            {
                return ResourceManager.GetString("Telefone", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Teve ou tem convulsões?.
        /// </summary>
        public static string TemConvulsao
        {
            get
            {
                return ResourceManager.GetString("TemConvulsao", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Tempo para atingir o peso mínimo.
        /// </summary>
        public static string TempoAtingirPesoMinimo
        {
            get
            {
                return ResourceManager.GetString("TempoAtingirPesoMinimo", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Duração da cirurgia.
        /// </summary>
        public static string TempoCirurgia
        {
            get
            {
                return ResourceManager.GetString("TempoCirurgia", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to O paciente nasceu com quantos meses?.
        /// </summary>
        public static string TempoNascimento
        {
            get
            {
                return ResourceManager.GetString("TempoNascimento", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Tempo da obesidade.
        /// </summary>
        public static string TempoObesidade
        {
            get
            {
                return ResourceManager.GetString("TempoObesidade", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Desde quando o problema foi observado?.
        /// </summary>
        public static string TempoProblemaFoiObservado
        {
            get
            {
                return ResourceManager.GetString("TempoProblemaFoiObservado", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Tempo de tratamento pré-operatório.
        /// </summary>
        public static string TempoTratamentoPreOperatorio
        {
            get
            {
                return ResourceManager.GetString("TempoTratamentoPreOperatorio", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Tibial posterior.
        /// </summary>
        public static string TibialPosterior
        {
            get
            {
                return ResourceManager.GetString("TibialPosterior", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Tipo.
        /// </summary>
        public static string Tipo
        {
            get
            {
                return ResourceManager.GetString("Tipo", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Tipo da cirurgia.
        /// </summary>
        public static string TipoCirurgia
        {
            get
            {
                return ResourceManager.GetString("TipoCirurgia", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Tipo do Exame.
        /// </summary>
        public static string TipoExame
        {
            get
            {
                return ResourceManager.GetString("TipoExame", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Qual tipo de parto?.
        /// </summary>
        public static string TipoParto
        {
            get
            {
                return ResourceManager.GetString("TipoParto", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Tramento psiquiátrico.
        /// </summary>
        public static string TratamentoPsiquiatrico
        {
            get
            {
                return ResourceManager.GetString("TratamentoPsiquiatrico", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to TVP.
        /// </summary>
        public static string TVP
        {
            get
            {
                return ResourceManager.GetString("TVP", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Ultrasonografia abdome total.
        /// </summary>
        public static string UltraSonografiaAbdomeTotal
        {
            get
            {
                return ResourceManager.GetString("UltraSonografiaAbdomeTotal", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Faz uso de medicações.
        /// </summary>
        public static string UsoMedicacoes
        {
            get
            {
                return ResourceManager.GetString("UsoMedicacoes", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Uso de medicamentos.
        /// </summary>
        public static string UsoMedicamentos
        {
            get
            {
                return ResourceManager.GetString("UsoMedicamentos", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Uso de suplementos.
        /// </summary>
        public static string UsoSuplementos
        {
            get
            {
                return ResourceManager.GetString("UsoSuplementos", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Usuário.
        /// </summary>
        public static string Usuario
        {
            get
            {
                return ResourceManager.GetString("Usuario", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to UTI Pós-operatório.
        /// </summary>
        public static string UTIPosOperatorio
        {
            get
            {
                return ResourceManager.GetString("UTIPosOperatorio", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Valor.
        /// </summary>
        public static string Valor
        {
            get
            {
                return ResourceManager.GetString("Valor", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Varizes MMII.
        /// </summary>
        public static string VarizesMMII
        {
            get
            {
                return ResourceManager.GetString("VarizesMMII", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Verduras.
        /// </summary>
        public static string Verduras
        {
            get
            {
                return ResourceManager.GetString("Verduras", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Vômitos.
        /// </summary>
        public static string Vomitos
        {
            get
            {
                return ResourceManager.GetString("Vomitos", resourceCulture);
            }
        }
    }
}
