//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

using System.ComponentModel.DataAnnotations;

namespace Model
{
    public partial class EstadoModel : BaseModel
    {
        #region Primitive Properties
    	
    	public override String ComboboxText { get; set; }
    	
    	[ScaffoldColumn(false)]
    	public override int Id
    	{
    		get;
    		set;
    	}
    
    	[Required(ErrorMessageResourceName = "Required", ErrorMessageResourceType = typeof(Util.Internationalization))]
    
    
    	[Display(Name = "Nome", Prompt = "Nome", ResourceType = typeof(Util.Internationalization))]
    	public virtual string Nome
        {
    		get;
    		set;
    
        }
    	[Required(ErrorMessageResourceName = "Required", ErrorMessageResourceType = typeof(Util.Internationalization))]
    
    
    	[Display(Name = "Sigla", Prompt = "Sigla", ResourceType = typeof(Util.Internationalization))]
    	public virtual string Sigla
        {
    		get;
    		set;
    
        }
        #endregion
        #region Navigation Properties
    
        public virtual ICollection<CidadeModel> Cidade
        {
            get
            {
                if (_cidade == null)
                {
                    var newCollection = new FixupCollection<CidadeModel>();
                    newCollection.CollectionChanged += FixupCidade;
                    _cidade = newCollection;
                }
                return _cidade;
            }
            set
            {
                if (!ReferenceEquals(_cidade, value))
                {
                    var previousValue = _cidade as FixupCollection<CidadeModel>;
                    if (previousValue != null)
                    {
                        previousValue.CollectionChanged -= FixupCidade;
                    }
                    _cidade = value;
                    var newValue = value as FixupCollection<CidadeModel>;
                    if (newValue != null)
                    {
                        newValue.CollectionChanged += FixupCidade;
                    }
                }
            }
        }
        private ICollection<CidadeModel> _cidade;

        #endregion
        #region Association Fixup
    
        private void FixupCidade(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (e.NewItems != null)
            {
                foreach (CidadeModel item in e.NewItems)
                {
                    item.Estado = this;
                }
            }
    
            if (e.OldItems != null)
            {
                foreach (CidadeModel item in e.OldItems)
                {
                    if (ReferenceEquals(item.Estado, this))
                    {
                        item.Estado = null;
                    }
                }
            }
        }

        #endregion
    }
}
