//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

using System.ComponentModel.DataAnnotations;

namespace Model
{
    public partial class LoginModel : BaseModel
    {
        #region Primitive Properties
    	
    	public override String ComboboxText { get; set; }
    	
    	[ScaffoldColumn(false)]
    	public override int Id
    	{
    		get;
    		set;
    	}
    
    	[Required(ErrorMessageResourceName = "Required", ErrorMessageResourceType = typeof(Util.Internationalization))]
    
    
    	[Display(Name = "Password", Prompt = "Password", ResourceType = typeof(Util.Internationalization))]
    	public virtual string Password
        {
    		get;
    		set;
    
        }
    	[Required(ErrorMessageResourceName = "Required", ErrorMessageResourceType = typeof(Util.Internationalization))]
    
    
    	[Display(Name = "Email", Prompt = "Email", ResourceType = typeof(Util.Internationalization))]
    	public virtual string Email
        {
    		get;
    		set;
    
        }
        #endregion
        #region Navigation Properties
    
        public virtual PerfilModel Perfil
        {
            get { return _perfil; }
            set
            {
                if (!ReferenceEquals(_perfil, value))
                {
                    var previousValue = _perfil;
                    _perfil = value;
                    FixupPerfil(previousValue);
                }
            }
        }
        private PerfilModel _perfil;

        #endregion
        #region Association Fixup
    
        private void FixupPerfil(PerfilModel previousValue)
        {
            if (previousValue != null && previousValue.Login.Contains(this))
            {
                previousValue.Login.Remove(this);
            }
    
            if (Perfil != null)
            {
                if (!Perfil.Login.Contains(this))
                {
                    Perfil.Login.Add(this);
                }
            }
        }

        #endregion
    }
}
