//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.EntityClient;

namespace DAL.Data
{
    public partial class DataModelContainer : ObjectContext
    {
        public const string ConnectionString = "name=DataModelContainer";
        public const string ContainerName = "DataModelContainer";
    
        #region Constructors
    
        public DataModelContainer()
            : base(ConnectionString, ContainerName)
        {
            this.ContextOptions.LazyLoadingEnabled = true;
        }
    
    //    public DataModelContainer(string connectionString)
    //        : base(connectionString, ContainerName)
    //    {
    //    }
    
    //    public DataModelContainer(EntityConnection connection)
    //        : base(connection, ContainerName)
    //    {
    //    }
    
        #endregion
    
        #region ObjectSet Properties
    
        public ObjectSet<Login> Login
        {
            get { return _login  ?? (_login = CreateObjectSet<Login>("Login")); }
        }
        private ObjectSet<Login> _login;
    
        public ObjectSet<Perfil> Perfil
        {
            get { return _perfil  ?? (_perfil = CreateObjectSet<Perfil>("Perfil")); }
        }
        private ObjectSet<Perfil> _perfil;
    
        public ObjectSet<Menu> Menu
        {
            get { return _menu  ?? (_menu = CreateObjectSet<Menu>("Menu")); }
        }
        private ObjectSet<Menu> _menu;
    
        public ObjectSet<SubMenu> SubMenu
        {
            get { return _subMenu  ?? (_subMenu = CreateObjectSet<SubMenu>("SubMenu")); }
        }
        private ObjectSet<SubMenu> _subMenu;

        #endregion
    }
}
