//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

using System.Linq;
using Model;

namespace DAL
{
    public partial class Cidade
    {
    
    	public string ComboboxText{ get; set; }
    
    	public static Cidade GetCidade(int p_Identifier)
    	{
    		DataContext v_Context = DataContext.GetContext();
            Cidade v_Data =
    					(from entity in v_Context.Cidade
                        where entity.Id == p_Identifier
    					select entity).FirstOrDefault();
    		if(v_Data!=null)
    			v_Data.setCombobox();
    		return v_Data;
    	}
    
    
    
    	public static ICollection<Cidade> ListCidade()
    	{
    		DataContext v_Context = DataContext.GetContext();
    		List<Cidade> v_List =v_Context.Cidade.ToList();
    		for(int i=0; i < v_List.Count(); i++)
    		{
    			v_List[i].setCombobox();
    		}
    		return v_List;
    	}
    
    	
    
        public static void DeleteCidade(int p_Identifier)
        {
            DataContext v_Context = DataContext.GetContext();
            Cidade CidadeDAL = GetCidade(p_Identifier);
            v_Context.DeleteObject(CidadeDAL);
        }
    
    
    	public static Cidade CreateFactory(Model.CidadeModel p_Model)
    	{
    		if(p_Model == null)
    			return new Cidade();
    		Cidade v_NewCidade = new Cidade();
    		v_NewCidade.Id = p_Model.Id;
    		v_NewCidade.Nome = p_Model.Nome;
            if (p_Model.Estado != null)
    			v_NewCidade.Estado = Estado.GetEstado(p_Model.Estado.Id);
    		if (v_NewCidade.Estado == null)
    			throw new Exception("Entidade Cidade deve ter um(a) Estado associado.");
    		v_NewCidade.ComboboxText = p_Model.ComboboxText;
    		return v_NewCidade;
    	}
    
    	public static void Create(Model.CidadeModel p_Model)
    	{
    		DataContext v_Context = DataContext.GetContext();
    		Cidade v_NewCidade = CreateFactory(p_Model);
    
    
    	}
    
    	public static void Edit(Model.CidadeModel p_Model)
    	{
    		if(p_Model == null || p_Model.Id == 0)
    			return;
    		DataContext v_Context = DataContext.GetContext();
    		Cidade v_Cidade = GetCidade(p_Model.Id);
    		v_Cidade.updateFields(p_Model);
    }
    
    	
    	public void updateFields(CidadeModel p_Model)
        {
    		if(p_Model == null)
    			return ;
    
    		this.Nome = p_Model.Nome;
    	}
    
    
    	public void delete()
    	{
    		DataContext v_Context = DataContext.GetContext();
    		v_Context.DeleteObject(this);
    	}
    }
}
