//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

using System.Linq;
using Model;

namespace DAL
{
    public partial class Estado
    {
    
    	public string ComboboxText{ get; set; }
    
    	public static Estado GetEstado(int p_Identifier)
    	{
    		DataContext v_Context = DataContext.GetContext();
            Estado v_Data =
    					(from entity in v_Context.Estado
                        where entity.Id == p_Identifier
    					select entity).FirstOrDefault();
    		if(v_Data!=null)
    			v_Data.setCombobox();
    		return v_Data;
    	}
    
    
    
    	public static ICollection<Estado> ListEstado()
    	{
    		DataContext v_Context = DataContext.GetContext();
    		List<Estado> v_List =v_Context.Estado.ToList();
    		for(int i=0; i < v_List.Count(); i++)
    		{
    			v_List[i].setCombobox();
    		}
    		return v_List;
    	}
    
    	
    
        public static void DeleteEstado(int p_Identifier)
        {
            DataContext v_Context = DataContext.GetContext();
            Estado EstadoDAL = GetEstado(p_Identifier);
            v_Context.DeleteObject(EstadoDAL);
        }
    
    
    	public static Estado CreateFactory(Model.EstadoModel p_Model)
    	{
    		if(p_Model == null)
    			return new Estado();
    		Estado v_NewEstado = new Estado();
    		v_NewEstado.Id = p_Model.Id;
    		v_NewEstado.Nome = p_Model.Nome;
    		v_NewEstado.Sigla = p_Model.Sigla;
    		v_NewEstado.ComboboxText = p_Model.ComboboxText;
    		return v_NewEstado;
    	}
    
    	public static void Create(Model.EstadoModel p_Model)
    	{
    		DataContext v_Context = DataContext.GetContext();
    		Estado v_NewEstado = CreateFactory(p_Model);
    
    
    	}
    
    	public static void Edit(Model.EstadoModel p_Model)
    	{
    		if(p_Model == null || p_Model.Id == 0)
    			return;
    		DataContext v_Context = DataContext.GetContext();
    		Estado v_Estado = GetEstado(p_Model.Id);
    		v_Estado.updateFields(p_Model);
    }
    
    	
    	public void updateFields(EstadoModel p_Model)
        {
    		if(p_Model == null)
    			return ;
    
    		this.Nome = p_Model.Nome;
    		this.Sigla = p_Model.Sigla;
    	}
    
    
    	public void delete()
    	{
    		DataContext v_Context = DataContext.GetContext();
    		v_Context.DeleteObject(this);
    	}
    }
}
