//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

using System.Linq;
using Model;

namespace DAL
{
    public partial class Menu
    {
    
    	public string ComboboxText{ get; set; }
    
    	public static Menu GetMenu(int p_Identifier)
    	{
    		DataContext v_Context = DataContext.GetContext();
            Menu v_Data =
    					(from entity in v_Context.Menu
                        where entity.Id == p_Identifier
    					select entity).FirstOrDefault();
    		if(v_Data!=null)
    			v_Data.setCombobox();
    		return v_Data;
    	}
    
    
    
    	public static ICollection<Menu> ListMenu()
    	{
    		DataContext v_Context = DataContext.GetContext();
    		List<Menu> v_List =v_Context.Menu.ToList();
    		for(int i=0; i < v_List.Count(); i++)
    		{
    			v_List[i].setCombobox();
    		}
    		return v_List;
    	}
    
    	
    
        public static void DeleteMenu(int p_Identifier)
        {
            DataContext v_Context = DataContext.GetContext();
            Menu MenuDAL = GetMenu(p_Identifier);
            v_Context.DeleteObject(MenuDAL);
        }
    
    
    	public static Menu CreateFactory(Model.MenuModel p_Model)
    	{
    		if(p_Model == null)
    			return new Menu();
    		Menu v_NewMenu = new Menu();
    		v_NewMenu.Id = p_Model.Id;
    		v_NewMenu.Name = p_Model.Name;
    		v_NewMenu.ClassName = p_Model.ClassName;
    		v_NewMenu.ComboboxText = p_Model.ComboboxText;
    		return v_NewMenu;
    	}
    
    	public static void Create(Model.MenuModel p_Model)
    	{
    		DataContext v_Context = DataContext.GetContext();
    		Menu v_NewMenu = CreateFactory(p_Model);
    
    
    	}
    
    	public static void Edit(Model.MenuModel p_Model)
    	{
    		if(p_Model == null || p_Model.Id == 0)
    			return;
    		DataContext v_Context = DataContext.GetContext();
    		Menu v_Menu = GetMenu(p_Model.Id);
    		v_Menu.updateFields(p_Model);
    }
    
    	
    	public void updateFields(MenuModel p_Model)
        {
    		if(p_Model == null)
    			return ;
    
    		this.Name = p_Model.Name;
    		this.ClassName = p_Model.ClassName;
    	}
    
    
    	public void delete()
    	{
    		DataContext v_Context = DataContext.GetContext();
    		v_Context.DeleteObject(this);
    	}
    }
}
