//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

using DAL;
using Model;
using BLL;

namespace DataController
{
    public partial class MasterDataController
    {
    
    	public SubMenuModel GetSubMenu(int p_Identifier)
    	{
    		return BLL.SubMenuBLL.GetSubMenu(p_Identifier);
    	}
    
    	public SubMenuModel GetSubMenu(int p_Identifier, BLL.DTOQuery.SubMenuDTOQuery p_SubMenuQuery)
        {
            return BLL.SubMenuBLL.GetSubMenu(p_Identifier, p_SubMenuQuery);
        }
    
    	public ICollection<SubMenuModel> ListSubMenu()
    	{
    		return BLL.SubMenuBLL.ListSubMenu();
    	}
    
    	public void DeleteSubMenu(int p_Identifier)
    	{
    		BLL.SubMenuBLL.DeleteSubMenu(p_Identifier);
    	}
    
    	public void CreateSubMenu(SubMenuModel p_Model)
    	{
    		BLL.SubMenuBLL.CreateSubMenu(p_Model);
    	}
    
    	public void EditSubMenu(SubMenuModel p_Model)
    	{
    		BLL.SubMenuBLL.EditSubMenu(p_Model);
    	}
    
    }
}
