//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

using DAL;
using Model;
using BLL;

namespace DataController
{
    public partial class MasterDataController
    {
    
    	public MenuModel GetMenu(int p_Identifier)
    	{
    		return BLL.MenuBLL.GetMenu(p_Identifier);
    	}
    
    	public MenuModel GetMenu(int p_Identifier, BLL.DTOQuery.MenuDTOQuery p_MenuQuery)
        {
            return BLL.MenuBLL.GetMenu(p_Identifier, p_MenuQuery);
        }
    
    	public ICollection<MenuModel> ListMenu()
    	{
    		return BLL.MenuBLL.ListMenu();
    	}
    
    	public void DeleteMenu(int p_Identifier)
    	{
    		BLL.MenuBLL.DeleteMenu(p_Identifier);
    	}
    
    	public void CreateMenu(MenuModel p_Model)
    	{
    		BLL.MenuBLL.CreateMenu(p_Model);
    	}
    
    	public void EditMenu(MenuModel p_Model)
    	{
    		BLL.MenuBLL.EditMenu(p_Model);
    	}
    
    }
}
