//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

using DAL;
using Model;
using BLL;

namespace DataController
{
    public partial class MasterDataController
    {
    
    	public PerfilModel GetPerfil(int p_Identifier)
    	{
    		return BLL.PerfilBLL.GetPerfil(p_Identifier);
    	}
    
    	public PerfilModel GetPerfil(int p_Identifier, BLL.DTOQuery.PerfilDTOQuery p_PerfilQuery)
        {
            return BLL.PerfilBLL.GetPerfil(p_Identifier, p_PerfilQuery);
        }
    
    	public ICollection<PerfilModel> ListPerfil()
    	{
    		return BLL.PerfilBLL.ListPerfil();
    	}
    
    	public void DeletePerfil(int p_Identifier)
    	{
    		BLL.PerfilBLL.DeletePerfil(p_Identifier);
    	}
    
    	public void CreatePerfil(PerfilModel p_Model)
    	{
    		BLL.PerfilBLL.CreatePerfil(p_Model);
    	}
    
    	public void EditPerfil(PerfilModel p_Model)
    	{
    		BLL.PerfilBLL.EditPerfil(p_Model);
    	}
    
    }
}
