//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

using DAL;
using Model;
using BLL;

namespace DataController
{
    public partial class MasterDataController
    {
    
    	public CidadeModel GetCidade(int p_Identifier)
    	{
    		return BLL.CidadeBLL.GetCidade(p_Identifier);
    	}
    
    	public CidadeModel GetCidade(int p_Identifier, BLL.DTOQuery.CidadeDTOQuery p_CidadeQuery)
        {
            return BLL.CidadeBLL.GetCidade(p_Identifier, p_CidadeQuery);
        }
    
    	public ICollection<CidadeModel> ListCidade()
    	{
    		return BLL.CidadeBLL.ListCidade();
    	}
    
    	public void DeleteCidade(int p_Identifier)
    	{
    		BLL.CidadeBLL.DeleteCidade(p_Identifier);
    	}
    
    	public void CreateCidade(CidadeModel p_Model)
    	{
    		BLL.CidadeBLL.CreateCidade(p_Model);
    	}
    
    	public void EditCidade(CidadeModel p_Model)
    	{
    		BLL.CidadeBLL.EditCidade(p_Model);
    	}
    
    }
}
