//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

using DAL;
using Model;
using BLL;

namespace DataController
{
    public partial class MasterDataController
    {
    
    	public EstadoModel GetEstado(int p_Identifier)
    	{
    		return BLL.EstadoBLL.GetEstado(p_Identifier);
    	}
    
    	public EstadoModel GetEstado(int p_Identifier, BLL.DTOQuery.EstadoDTOQuery p_EstadoQuery)
        {
            return BLL.EstadoBLL.GetEstado(p_Identifier, p_EstadoQuery);
        }
    
    	public ICollection<EstadoModel> ListEstado()
    	{
    		return BLL.EstadoBLL.ListEstado();
    	}
    
    	public void DeleteEstado(int p_Identifier)
    	{
    		BLL.EstadoBLL.DeleteEstado(p_Identifier);
    	}
    
    	public void CreateEstado(EstadoModel p_Model)
    	{
    		BLL.EstadoBLL.CreateEstado(p_Model);
    	}
    
    	public void EditEstado(EstadoModel p_Model)
    	{
    		BLL.EstadoBLL.EditEstado(p_Model);
    	}
    
    }
}
